name: publish

on:
  push:
    branches:
      - "main"
    paths:
      - CHANGELOG.md

jobs:
  publish-npm:
    name: Publish to vscode marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm
      - run: npm ci
      - name: Build code
        run: npm run ci:build
      - name: Publish
        run: node_modules/.bin/vsce publish -p ${{ secrets.VSCODE_TOKEN }}
