name: publish

on:
  push:
    # branches:
    #   - "main"
    # paths:
    #   - CHANGELOG.md

jobs:
  publish:
    name: Publish to vscode marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm
      - run: npm ci
      - name: Build code
        run: npm run ci:build
      # - name: Publish
      #   run: node_modules/.bin/vsce publish -p ${{ secrets.VSCODE_TOKEN }}

      - name: Create a new tag
        run: yarn ci:tag
        env:
          GITHUBTOKEN: ${{ secrets.GIT_TOKEN }}
          LASTCOMMITSHA: ${{ github.SHA }}

      - name: Create a new release
        run: yarn ci:release
        env:
          TAG: ${{ github.ref_name }}
          GITHUBTOKEN: ${{ secrets.GIT_TOKEN }}
