name: publish

on:
  repository_dispatch:
    types: [new_ymlr]

jobs:
  publish:
    name: Publish to vscode marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm
      - run: npm ci
      - run: npm install ymlr@${{ github.event.client_payload.version }} --save
      - name: Update version
        run: npm version --no-commit-hooks --no-git-tag-version ${{ github.event.client_payload.version }}
      - name: Build code
        run: npm run ci:build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: v${{ github.event.client_payload.version }}
      - name: Publish
        run: node_modules/.bin/vsce publish -p ${{ secrets.VSCODE_TOKEN }}
